name: daily_quest
description: "Daily Quest App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_analytics: ^10.10.2
  cloud_firestore: ^4.4.5
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16

  get: ^4.6.5
  flutter_local_notifications: 14.0.0
  json_annotation: ^4.8.0
  jiffy: 4.0.0
  firebase_database: ^10.0.16
  intl: 0.17.0
  image_picker: 0.8.6
  in_app_purchase: 3.1.5
  shared_preferences: ^2.0.20
  kakao_flutter_sdk: ^1.9.1+2
  freezed: ^2.5.2
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/kakao/
    - .env
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
